---
# This playbook can install Red Hat Decision Manager in multiple flavours:

# 1. RHDM Central (Business Central / Workbench).
- name: provision RHDM Central
  hosts: central
  tasks:
    - import_role:
        name: rhdm-central
    - import_role:
        name: jboss-eap-service
      vars:
        jboss_eap_svc_home: "{{ jboss_eap_home }}"
  post_tasks:
    - debug:
        msg:
          - "Installation dir: {{ rhdm_central_root }}"
          - "URL: http://{{ inventory_hostname }}:{{ jboss_http_port_number }}/decision-central"
          - "User admin username: {{ rhdm_central_admin_usr }}"
          - "User admin password: {{ rhdm_central_admin_pwd }}"
          - "SSH key: {{ openssh_keypair.public_key }}"

# 2. RHDM Server (KIE Server) unmanaged or managed, via the 'org_kie_server_controller' variable.
- name: provision RHDM Server
  hosts: server:managed
  tasks:
    - import_role:
        name: rhdm-server
    - import_role:
        name: jboss-eap-service
      vars:
        jboss_eap_svc_home: "{{ jboss_eap_home }}"
  post_tasks:
    - debug:
        msg:
          - "Installation dir: {{ rhdm_server_root }}"
          - "URL: http://{{ inventory_hostname }}:{{ org_kie_server_http_port }}/kie-server/services/rest/server"
          - "User kieserver username: {{ rhdm_server_kieserver_usr }}"
          - "User kieserver password: {{ rhdm_server_kieserver_pwd }}"

# 3. RHDM Central and Server on the same host.
#    The KIE Server is in managed mode and automatically connected to Central's contoller instance.
- name: provision RHDM Central and RHDM Server on the same host
  hosts: hybrid
  tasks:
    - include_role:
        name: rhdm-central
      vars:
        jboss_socket_binding_port_offset_number: 100
    - include_role:
        name: rhdm-server
      vars:
        jboss_socket_binding_port_offset_number: 0
        org_kie_server_controller: ws://localhost:8180/decision-central/websocket/controller
  post_tasks:
    - debug:
        msg:
          - "Run Central: nohup $RHDM_CENTRAL_HOME/bin/standalone.sh -c standalone-full.xml > central.log &"
          - "Run Server: nohup $RHDM_SERVER_HOME/bin/standalone.sh -c standalone-full.xml > server.log &"
          - "Central URL: http://{{ inventory_hostname }}:8180/decision-central"
          - "Server URL: http://{{ inventory_hostname }}:8080/kie-server/services/rest/server"
      tags: debug
