---
# RHEL 7 tested, run JBoss EAP as a systemd service.

- name: create /etc/default/jboss-eap.conf
  template:
    src: jboss-eap.conf.j2
    dest: /etc/default/jboss-eap.conf
  become: yes

- name: create /etc/systemd/system/jbosseap7.service
  template:
    src: jbosseap7.service.j2
    dest: /etc/systemd/system/jbosseap7.service
  become: yes

- name: enable service jbosseap7.service
  service:
    name: jbosseap7
    enabled: yes
  become: yes

- name: start service jbosseap7.service
  service:
    name: jbosseap7
    state: started
  become: yes
