---
- name: download JBoss EAP into {{ jboss_eap_temp }}
  get_url:
    url: "{{ jboss_eap_artifact_source }}/{{ jboss_eap_artifact_name }}"
    dest: "{{ jboss_eap_temp }}/{{ jboss_eap_artifact_name }}"

- name: extract JBoss EAP into {{ jboss_eap_temp }}
  unarchive:
    src: "{{ jboss_eap_temp }}/{{ jboss_eap_artifact_name }}"
    dest: "{{ jboss_eap_temp }}"
    remote_src: yes

- name: create JBoss EAP home {{ jboss_eap_home }}
  file:
    path: "{{ jboss_eap_home }}"
    state: directory

- name: copy JBoss EAP to home {{ jboss_eap_home }}
  command:
    cmd: "cp -rf {{ jboss_eap_temp }}/{{ jboss_eap_path }}/. {{ jboss_eap_home }}/"
    creates: "{{ jboss_eap_home }}/bin"
