---
- name: download JBoss EAP patches
  get_url:
    url: "{{ jboss_eap_artifact_source }}/{{ item }}"
    dest: "{{ jboss_eap_temp }}/{{ item }}"
  loop: "{{ jboss_eap_patch_artifact_names }}"
  ignore_errors: yes

- name: find downloaded JBoss patches
  find:
    path: "{{ jboss_eap_temp }}"
    pattern: "{{ jboss_eap_patch_artifact_pattern }}"
  register: jboss_eap_patch_artifact_files

- name: create {{ jboss_eap_patches }} marker directory
  file:
    path: "{{ jboss_eap_patches }}"
    state: directory

- name: apply JBoss EAP patches
  shell:
    cmd: "{{ jboss_eap_home }}/bin/jboss-cli.sh --command='patch apply {{ item }}' && touch {{ jboss_eap_patches }}/{{ item | basename }}.applied"
    creates: "{{ jboss_eap_patches }}/{{ item | basename }}.applied"
  loop: "{{ jboss_eap_patch_artifact_files.files | sort(attribute='path') | map(attribute='path') | list }}"
