---
- name: install software packages in RHEL7
  yum:
    name:
      - java-1.8.0-openjdk-devel
      - unzip
      - git
    state: present
  become: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
