---
- name: download RHDM Server into {{ rhdm_server_temp }}
  get_url:
    url: "{{ rhdm_server_artifact_source }}/{{ rhdm_server_artifact_name }}"
    dest: "{{ rhdm_server_temp }}/{{ rhdm_server_artifact_name }}"

- name: extract RHDM Server into {{ rhdm_server_temp }}
  unarchive:
    src: "{{ rhdm_server_temp }}/{{ rhdm_server_artifact_name }}"
    dest: "{{ rhdm_server_temp }}"
    remote_src: yes

- name: copy SecurityPolicy to {{ rhdm_server_home }}/bin/
  command:
    cmd: "cp -rf {{ rhdm_server_temp }}/SecurityPolicy/. {{ rhdm_server_home }}/bin/"
    creates: "{{ rhdm_server_home }}/bin/security.policy"

- name: copy kie-server.war to {{ rhdm_server_home }}/standalone/deployments/
  command:
    cmd: "cp -rf {{ rhdm_server_temp }}/kie-server.war {{ rhdm_server_home }}/standalone/deployments/"
    creates: "{{ rhdm_server_home }}/standalone/deployments/kie-server.war"

- name: check if kie-server.war.deployed exists
  stat:
    path: "{{ rhdm_server_home }}/standalone/deployments/kie-server.war.deployed"
  register: kieserver_deployed

- name: create kie-server.war.dodeploy
  file:
    path: "{{ rhdm_server_home }}/standalone/deployments/kie-server.war.dodeploy"
    state: touch
  when: not kieserver_deployed.stat.exists
