---
- name: create {{ rhdm_server_temp }} installation directory
  file:
    path: "{{ rhdm_server_temp }}"
    state: directory

- import_tasks: setup.yml

- import_tasks: setup-managed.yml
  when: org_kie_server_controller is defined

- import_tasks: install.yml
