---
- name: create {{ rhdm_server_data }} directory
  file:
    path: "{{ rhdm_server_data }}"
    state: directory

- name: add kieserver user {{ rhdm_server_kieserver_usr }}
  command: "{{ rhdm_server_home }}/bin/add-user.sh -a --user {{ rhdm_server_kieserver_usr }} --password {{ rhdm_server_kieserver_pwd }} --role kie-server"

- name: create {{ kie_maven_settings_custom }}
  template:
    src: settings.xml.j2
    dest: "{{ kie_maven_settings_custom }}"

- name: create setup.cli
  template:
    src: setup.cli.j2
    dest: "{{ rhdm_server_temp }}/setup.cli"

- name: run setup.cli JBoss configuration
  command: "{{ rhdm_server_home }}/bin/jboss-cli.sh --file={{ rhdm_server_temp }}/setup.cli"
