---
- name: download RHDM Central into {{ rhdm_central_temp }}
  get_url:
    url: "{{ rhdm_central_artifact_source }}/{{ rhdm_central_artifact_name }}"
    dest: "{{ rhdm_central_temp }}/{{ rhdm_central_artifact_name }}"

- name: extract RHDM Central into {{ rhdm_central_temp }}
  unarchive:
    src: "{{ rhdm_central_temp }}/{{ rhdm_central_artifact_name }}"
    dest: "{{ rhdm_central_temp }}"
    remote_src: yes

- name: remove extracted standalone-full.xml to avoid overwrite
  file:
    path: "{{ rhdm_central_temp }}/{{ jboss_eap_path }}/standalone/configuration/standalone-full.xml"
    state: absent

- name: install RHDM Central files on {{ rhdm_central_home }}
  command:
    cmd: "cp -rf {{ rhdm_central_temp }}/{{ jboss_eap_path }}/. {{ rhdm_central_home }}/"
    creates: "{{ rhdm_central_home }}/standalone/deployments/decision-central.war"
